chore(lint): refining linting and git hooks

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -16,7 +16,7 @@ export NVM_DIR="$HOME/.nvm"
 if [ -s "$NVM_DIR/nvm.sh" ]; then
   . "$NVM_DIR/nvm.sh"
 else
-  echo "pre-commit: nvm.sh not found at $NVM_DIR/nvm.sh" >&2
+  echo "commit-msg: nvm.sh not found at $NVM_DIR/nvm.sh" >&2
   exit 1
 fi
 
@@ -31,5 +31,6 @@ else
   }
 fi
 
-# --- Run your pre-commit commands -------------------------------------
-./node_modules/.bin/lint-staged
+# --- Run your commit-msg commands -------------------------------------
+./node_modules/.bin/commitlint --edit "$1"
+# npm run commitlint -- --edit "$1"
